import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { PageShell } from "@/components/arrena-shell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";

export const Route = createFileRoute("/add")({ head: () => ({ meta: [{ title: "Add Your Community — ARRENA" }, { name: "description", content: "Add your gaming community and enter the ARRENA ranking." }, { property: "og:title", content: "Add Your Community — ARRENA" }, { property: "og:description", content: "Enter the competitive ranking marketplace for gaming communities." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: AddPage });

const steps = ["Choose platform", "Community details", "Starting bid", "Preview", "Enter the Arena"];
function AddPage() { const [step, setStep] = useState(0); const [platform, setPlatform] = useState("Minecraft"); return <PageShell><div className="mx-auto min-h-[75vh] max-w-2xl px-4 py-10 sm:px-6 sm:py-16"><div className="flex items-center justify-between"><p className="text-xs font-semibold uppercase text-primary">Add Community</p><span className="text-xs text-muted-foreground">0{step+1} / 05</span></div><div className="mt-4 h-1 overflow-hidden rounded-full bg-secondary"><div className="h-full bg-primary transition-all" style={{ width: `${((step+1)/5)*100}%` }} /></div><h1 className="mt-10 text-3xl font-semibold">{steps[step]}</h1><div className="mt-8 min-h-64">{step === 0 && <div className="grid grid-cols-2 gap-3">{["Minecraft","CS2","Discord","Telegram"].map((item) => <Button key={item} variant={platform === item ? "default" : "outline"} className="h-16" onClick={() => setPlatform(item)}>{item}</Button>)}</div>}{step === 1 && <div className="space-y-5"><div><label className="mb-2 block text-sm font-medium">Name</label><Input placeholder="Minecraft Uzbekistan" /></div><div><label className="mb-2 block text-sm font-medium">Description</label><Textarea placeholder="Tell players what makes your community worth joining." /></div><div><label className="mb-2 block text-sm font-medium">URL / Server IP</label><Input placeholder="play.yourserver.uz" /></div></div>}{step === 2 && <div><label className="mb-2 block text-sm font-medium">Starting bid</label><Input defaultValue="300,000 UZS" className="h-12 text-lg" /><p className="mt-3 text-xs text-muted-foreground">The minimum entry bid is 300,000 UZS.</p></div>}{step === 3 && <div className="border-y border-border py-5"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-md bg-secondary font-display font-bold">YU</div><div><p className="font-display font-semibold">Your community</p><Badge variant="outline" className="mt-1">{platform}</Badge></div><div className="ml-auto text-right"><p className="font-display font-semibold text-primary">300,000 UZS</p><p className="text-xs text-muted-foreground">Estimated #24</p></div></div></div>}{step === 4 && <div className="rounded-md border border-border bg-card p-6"><p className="font-display text-xl font-semibold">Everything looks ready.</p><p className="mt-2 text-sm text-muted-foreground">Your community will enter at the highest position available for your starting bid.</p></div>}</div><div className="mt-8 flex justify-between border-t border-border pt-6"><Button variant="ghost" disabled={step === 0} onClick={() => setStep((value) => value-1)}>Back</Button><Button onClick={() => setStep((value) => Math.min(4,value+1))}>{step === 4 ? "Enter the Arena" : "Continue"}</Button></div></div></PageShell> }