import { createFileRoute, notFound } from "@tanstack/react-router";
import { PageShell } from "@/components/arrena-shell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { communities, formatUzs } from "@/lib/arrena-data";

export const Route = createFileRoute("/community/$id")({ loader: ({ params }) => { const community = communities.find((item) => item.id === params.id); if (!community) throw notFound(); return { community }; }, head: ({ loaderData }) => ({ meta: [{ title: loaderData ? `${loaderData.community.name} — ARRENA` : "Community unavailable — ARRENA" }, { name: "description", content: loaderData?.community.description ?? "This ARRENA community is unavailable." }, { property: "og:title", content: loaderData ? `${loaderData.community.name} — ARRENA` : "Community unavailable — ARRENA" }, { property: "og:description", content: loaderData?.community.description ?? "This ARRENA community is unavailable." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: CommunityPage });

function CommunityPage() { const { community } = Route.useLoaderData(); const minimum = community.bid + 200000; return <PageShell><article className="mx-auto min-h-[75vh] max-w-[960px] px-4 py-12 sm:px-6 sm:py-20"><div className="flex items-start gap-4"><div className="grid size-14 place-items-center rounded-2xl border border-primary/15 bg-secondary font-display font-bold">{community.initials}</div><div><Badge variant="outline">{community.platform}</Badge><h1 className="mt-3 text-4xl font-semibold sm:text-6xl">{community.name}</h1><p className="mt-3 max-w-xl text-muted-foreground">{community.description}</p><a href={community.link.startsWith("http") ? community.link : `https://${community.link}`} target="_blank" rel="noreferrer noopener" className="mt-3 inline-flex"><LinkChip link={community.link} className="transition-colors hover:text-foreground" /></a></div></div><div className="mt-12 grid gap-8 border-y border-border py-10 sm:grid-cols-3"><div><p className="font-display text-6xl font-semibold">#{community.rank}</p><p className="mt-2 text-xs text-muted-foreground">Current position</p></div><div><p className="font-display text-2xl font-semibold text-primary">{formatUzs(community.bid)}</p><p className="mt-2 text-xs text-muted-foreground">Current bid</p><p className="mt-6 font-display text-2xl font-semibold">{community.clicks.toLocaleString()}</p><p className="mt-2 text-xs text-muted-foreground">Clicks</p></div><div><p className={community.movement >= 0 ? "font-display text-2xl font-semibold text-positive" : "font-display text-2xl font-semibold text-negative"}>{community.movement >= 0 ? "↑" : "↓"} {Math.abs(community.movement)}</p><p className="mt-2 text-xs text-muted-foreground">Positions today</p><Dialog><DialogTrigger asChild><Button className="mt-8 w-full">Challenge this position</Button></DialogTrigger><DialogContent className="max-w-md"><DialogHeader><DialogTitle>Take the position</DialogTitle><DialogDescription>Submit a higher bid to move above #{community.rank}.</DialogDescription></DialogHeader><div className="grid grid-cols-2 gap-4 text-sm"><div><p className="text-muted-foreground">Current bid</p><p className="mt-1 font-medium">{formatUzs(community.bid)}</p></div><div><p className="text-muted-foreground">Minimum next bid</p><p className="mt-1 font-medium text-primary">{formatUzs(minimum)}</p></div></div><Input defaultValue={minimum.toLocaleString("en-US")} aria-label="Your bid" /><DialogFooter><Button className="w-full">Challenge #{community.rank}</Button></DialogFooter></DialogContent></Dialog></div></div></article></PageShell> }